name: ServerCore 1 8
version: '${project.version}'
main: com.github.cyberryan1.servercore18.ServerCore18
api-version: 1.8.8
softdepend: [ Vault ]
authors: [ CyberRyan ]
commands:
  gma:
  gmc:
  gmsp:
  gms:
  flight:
    aliases: [fly]
  tp:
    aliases: [teleport]
  tphere:
  tpo:
  tpohere:
  tptoggle:
  workbench:
    aliases: [wb, craft, craftingbench, cb]
  enderchest:
    aliases: [ec]
  invsee:
    aliases: [openinv]
  broadcast:
    aliases: [bc]
  rules: